Repository mdtraj/mdtraj, pull requests merged in 2025-05, with the labels that each got.

#1974 Test linux aarch64
  .github/workflows/main.yaml
  tests/test_distance.py
Labels: dependencies

#2011 Allow mdtraj.rmsd() to calculate without alignment
  mdtraj/rmsd/_rmsd.pyx
  tests/test_rmsd.py
Labels: api

#2015 Preserve chain_id when creating topologies
  mdtraj/core/topology.py
  mdtraj/formats/hdf5.py
  tests/test_topology.py
Labels: bug
